version: "3.8"

services:
  app:
    build: .
    image: robin-booking
    restart: "no"
    command: book
    environment:
      TZ: ${TZ}
    volumes:
      - ./:/usr/src/app
  chrome:
    image: selenium/standalone-chrome:108.0
    restart: unless-stopped
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: "2g"
