version: "3.8"

services:
  app:
    build: .
    image: robin-booking
    restart: "no"
    depends_on:
      - selenium-hub
    environment:
      TZ: ${TZ}
      SELENIUM_WEBDRIVER_URL: http://selenium-hub:4444/wd/hub
      ROBIN_CREDENTIALS: ${ROBIN_CREDENTIALS}
      ROBIN_USER_ID: ${ROBIN_USER_ID}
      ROBIN_ORGANIZATION_ID: ${ROBIN_ORGANIZATION_ID}
      ROBIN_SPACE_ID: ${ROBIN_SPACE_ID}
      ROBIN_LEVEL_ID: ${ROBIN_LEVEL_ID}
      ROBIN_SEATS_PRIORITY: ${ROBIN_SEATS_PRIORITY}
    links:
      - selenium-hub

  chrome:
    image: selenium/node-chrome:4.7.1-20221208
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  selenium-hub:
    image: selenium/hub:4.7.1-20221208
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
